/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DatabaseProxy;
import Controller.SearchBehavior;
import Model.Database;
import com.mongodb.DBObject;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Diogo
 */
public class SearchRecord extends javax.swing.JFrame {

    SearchBehavior behave;

    /**
     * Creates new form SearchRecord
     */
    DatabaseProxy dbp = new DatabaseProxy();
    DefaultListModel listModel;
    ArrayList<DBObject> searchResults;

    public SearchRecord() {
        setup();
    }

    public SearchRecord(SearchBehavior behave) {
        setup();
        this.behave = behave;
    }

    public void setup() {
        initComponents();

        Set<String> collections = dbp.getAllCollections();

        collectionsList.addItem("");
        for (String coll : collections) {
            collectionsList.addItem(coll.toString());
        }

        MouseListener mouse = new MouseAdapter() {

            public void mouseClicked(MouseEvent mouseEvent) {
                JList list = (JList) mouseEvent.getSource();
                if (mouseEvent.getClickCount() == 2) {
                    int index = list.locationToIndex(mouseEvent.getPoint());
                    System.out.println(index);
                    System.out.println(searchResults);
                    if (index >= 0) {
                        DBObject selectedObject = searchResults.get(index);
                        System.out.println(selectedObject);
                        
                        behave.PerformAction(selectedObject, collectionsList.getSelectedItem().toString());
                        closeWindow();
                    }

                }
            }

        };
        resultList.addMouseListener(mouse);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        collectionsList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList<>();
        searchButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search Record");

        collectionsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionsListActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(resultList);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(collectionsList, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backButton)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(88, 88, 88)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collectionsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void collectionsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionsListActionPerformed
        // TODO add your handling code here:
        Object selected = collectionsList.getSelectedItem();
        listModel = new DefaultListModel();
        switch (selected.toString()) {
            case "school":
                searchResults = dbp.getAllRecords("school");
                for (int i = 0; i < searchResults.size(); i++) {
                    String option = searchResults.get(i).get("title").toString() + " - "
                            + searchResults.get(i).get("version").toString();

                    listModel.addElement(option);
                }
                System.out.println("End");
                resultList.setModel(listModel);

                break;
            case "schoolLocation":
                searchResults = dbp.getAllRecords("schoolLocation");
                for (int i = 0; i < searchResults.size(); i++) {
                    String option = searchResults.get(i).get("classroom").toString();
                    listModel.addElement(option);
                }
                System.out.println("End");
                resultList.setModel(listModel);
                break;

            case "schoolHardware":
                searchResults = dbp.getAllRecords("schoolHardware");
                for (int i = 0; i < searchResults.size(); i++) {
                    String option = searchResults.get(i).get("machine").toString() + " - "
                            + searchResults.get(i).get("name").toString() + " - "
                            + searchResults.get(i).get("mac").toString();

                    listModel.addElement(option);
                }
                System.out.println("End");
                resultList.setModel(listModel);
                break;

            case "images":
                searchResults = dbp.getAllRecords("images");
                for (int i = 0; i < searchResults.size(); i++) {
                    String option = searchResults.get(i).get("image").toString();

                    listModel.addElement(option);
                }
                System.out.println("End");
                resultList.setModel(listModel);
                break;

        }


    }//GEN-LAST:event_collectionsListActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.setVisible(false);
        new Menu().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // db.getFieldNames(collectionsList.getSelectedItem().toString());
        searchResults = new ArrayList<DBObject>();
        listModel.removeAllElements();
        listModel.clear();
        searchResults = dbp.search(collectionsList.getSelectedItem().toString(), searchField.getText().toString());

        ArrayList<String> secondList = new ArrayList<String>();
        if (collectionsList.getSelectedItem().toString().equals("school")) {
            for (int i = 0; i < searchResults.size(); i++) {
                String option = searchResults.get(i).get("title").toString() + " - "
                        + searchResults.get(i).get("version").toString();

                secondList.add(option);

                listModel.addElement(option);
            }
            System.out.println("End");
            resultList.setModel(listModel);
        } else if (collectionsList.getSelectedItem().toString().equals("schoolLocation")) {
            for (int i = 0; i < searchResults.size(); i++) {
                String option = searchResults.get(i).get("classroom").toString();
                secondList.add(option);

                listModel.addElement(option);
            }
            System.out.println("End");
            resultList.setModel(listModel);
        } else if (collectionsList.getSelectedItem().toString().equals("schoolHardware")) {
            for (int i = 0; i < searchResults.size(); i++) {
                String option = searchResults.get(i).get("machine").toString() + " - "
                        + searchResults.get(i).get("name").toString() + " - "
                        + searchResults.get(i).get("mac").toString();
                secondList.add(option);

                listModel.addElement(option);
            }
            System.out.println("End");
            resultList.setModel(listModel);
        } else if (collectionsList.getSelectedItem().toString().equals("images")) {
            for (int i = 0; i < searchResults.size(); i++) {
                String option = searchResults.get(i).get("image").toString();

                listModel.addElement(option);
            }
            System.out.println("End");
            resultList.setModel(listModel);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    public void closeWindow(){
        this.setVisible(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> collectionsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> resultList;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
